### ISSUE TITLE
How I can set auto-inject false in cli and grunt-browserify?

### ISSUE THREAD

**Issue by caoglish** [davidguttman/cssify#16]
I saw your code has options call 'auto-inject', How I can set false value to auto-inject options in command line?  

also If I want to use grunt-browserify, how I can set false value in auto-inject in grunt-browserify?

The reason I doing this:
I am thinking of developing a greasemonkey script by using browserify. so I can separate css and js file in dev project folder and build them together.

if I can get this work. I can do the following code:

```
var css=require("./style.css");
GM_addStyle("css");
```

I know `require("./style.css")` can do the same, however I like to try auto-inject:false option

**Comment by faergeek** [comment]
For now you can pass `--auto-inject=` for now (yes, just nothing after `=`).
Sorry if it's toooooo late for response.

@davidguttman What about supporting `--no-auto-inject` flag or something like that for convenience?

**Comment by davidguttman** [comment]
Sounds good

**Comment by faergeek** [comment]
Now you can pass `--no-auto-inject` flag to disable auto-injection
