### ISSUE TITLE
References by absolute module path

### ISSUE THREAD

**Issue by cburgmer** [davidguttman/cssify#19]
When running

    ./node_modules/.bin/browserify -t cssify file.js > bundle.js

I receive a bundle with the specified CSS file included. However the item is specified using the absolute module path revealing the directory structure of the build machine:

```
...
img{border:1px solid #000}"; (require("/some/directory/node_modules/cssify"))(css); module.exports = css;
},{"/some/directory/node_modules/cssify":13}]
...
```

It sounds a bit like https://github.com/substack/node-browserify/issues/675 and https://github.com/substack/node-browserify/issues/657. However this should be fixed in the versions I am using (3.46.1 & 6.3.4). The version of cssify is 0.6.0.

I'd prefer not to expose the path if possible.

**Comment by davidguttman** [comment]
Fixed in `v-0.7.0`
