### ISSUE TITLE
Gulp: CSS to JSON 

### ISSUE THREAD

**Issue by binarykitchen** [davidguttman/cssify#20]
I like the idea to convert CSS into a JSON you can require(...) from any node.js app. Do you think you could create a Gulp plugin for that?

**Comment by neodigm** [comment]
I too like this idea.  I am building a Living Style Guide browser extension.  Thanks.

**Comment by faergeek** [comment]
Can you describe your use cases please? May be I could help

**Comment by neodigm** [comment]
A Living Style Guide chrome extension might allow designers / developers to browse component styles while actually on the production site.  I imagine a hierarchical menu based on BEM rule names that could be used to add/remove styles in real-time.  Generating that menu would be easy if the CSS were in JSON format.  Gulp task automation would make it 'Living'.  -Thanks

**Comment by faergeek** [comment]
@neodigm I think you'd better use PostCSS for that kind of functionality, `cssify` does not parse CSS in any way, sorry.

Take a look at https://github.com/aramk/CSSJSON or play with PostCSS, I'm not sure if it has some plugin for that or not.

**Comment by neodigm** [comment]
Great advise.  Thanks.

**Comment by faergeek** [comment]
As it's not responsibility of this project I'll close this issue
