### ISSUE TITLE
Concat CSS and output to css.bundle

### ISSUE THREAD

**Issue by MylesBorins** [davidguttman/cssify#21]
I'd love to see the ability to set and option and have all the css output as a file, rather than injected in the bundle.

This might be an amazing idea, it might also be complete feature creep.

I'm on the fence if this is something that makes sense as its own transform, or if it could be an option to cssify.  While it is nice to be able to have the css injected by javascript... it isn't so nice when you first load the page, or when your page is loaded in a browser with js turned off.

**Comment by davidguttman** [comment]
JS can be turned off? ;)

Sounds good to me! Curious if we'll run into any issues generating a separate bundle (would there be any weird interactions with something like `watchify`?). Know of any other transforms that output separate files?

**Comment by tamlyn** [comment]
I was looking for something like this and discovered webpack which is similar to browserify but supports bundling JS, CSS, images and whatever http://webpack.github.io

Not used it but looks interesting.

**Comment by faergeek** [comment]
@TheAlphaNerd @tamlyn  Are you still interested in this feature?
Did you ever use something like `partition-bundle` or `factor-bundle`?
I think that we could implement it with the help of these packages in some way.

**Comment by ahdinosaur** [comment]
from the conversation in https://github.com/davidguttman/cssify/pull/45#issuecomment-167536769, i just wrote [`bundle-cssify`](https://github.com/sheetify/bundle-cssify). keen to play around with how to achieve this feature through some modules.
