### ISSUE TITLE
css-modules and writing to disk

### ISSUE THREAD

**Issue by faergeek** [davidguttman/cssify#25]
I think it would be logical for this plugin to become slightly more feature-rich than it is now.

I would like to see `css-modules` support and writing to a file (through options, of course).
I can help with implementing both of them.

If file writing is going against the idea of this plugin, can you tell me how do you extract css from js in production?

**Comment by faergeek** [comment]
Also would be good to allow the user to tell which files to process.

**Comment by davidguttman** [comment]
Both sound great!

**Comment by faergeek** [comment]
I submitted two PRs #26 and #27 

To support writing to disk I think we need a new file functioning as a plugin, instead of transform.

**Comment by faergeek** [comment]
Or probably it's better to create a separate plugin for that if something like that does not exist.
Or somehow use `brfs` for that, any ideas?

**Comment by faergeek** [comment]
I think that disk writing should be dedicated to separate plugin/transform, so closing this.
