### ISSUE TITLE
es6 const syntax

### ISSUE THREAD

**Issue by thaiat** [davidguttman/cssify#31]
When upgrading to the latest (1.0.0) of cssify, i get an syntax error in :
https://github.com/davidguttman/cssify/blob/master/lib/index.js#L3
```
const through = require('through2')
^^^^^
SyntaxError: Use of const in strict mode.
```
Any idea what's going on ?

**Comment by faergeek** [comment]
Which version of node do you have?

**Comment by thaiat** [comment]
0.12

i unserstand that you changed the constraint to node >= 4.0 but do you really need that ?
const could be easily replace by var 
and es6 template string rewritten

this would give broader audience to your very useful transform ....

**Comment by faergeek** [comment]
Would you submit a PR for this change? :-)

**Comment by matisoffn** [comment]
+1 same problem.

**Comment by faergeek** [comment]
@matisoffn @thaiat I would like to fix it, but I'm too busy currently, would you like to submit a pull request to fix it?

**Comment by matisoffn** [comment]
Just swap `const` with `var` in the lib dir?

**Comment by faergeek** [comment]
No, Not just `s/const/var`, there are arrow functions and other features of ES6.

**Comment by matisoffn** [comment]
I don't know ES6 well enough, but I'll try and submit a PR.

**Comment by faergeek** [comment]
Ok, I'll help a bit if you need it.

**Comment by matisoffn** [comment]
Can someone please handle this if they get the chance?

**Comment by faergeek** [comment]
I'll submit a PR. I've got some time now :-)

**Comment by faergeek** [comment]
@matisoffn @thaiat Could you test my branch? I just tested with 0.12.0 and it works
